class Ntfsmac < Formula
  desc "NTFS read/write on Apple Silicon macOS via a libkrun microVM (ntfs-3g over NFS)"
  homepage "https://github.com/khr898/ntfsmac"
  # By default, download the prebuilt CLI binaries and scripts packaged in the GitHub release
  # to make installation extremely fast and robust (no local compiler toolchains required).
  url "https://github.com/khr898/ntfsmac/releases/download/v2.3.040926/ntfsmac-cli-v2.3.040926.tar.gz"
  version "2.3.040926"
  sha256 "7662968f516830b2ec8b1cd28d6945075b88fafa7227688ef4c4fc9d5b6ff054"
  license "MIT"

  # `brew install --HEAD` compiles from the latest main branch source code.
  head do
    url "https://github.com/khr898/ntfsmac.git", branch: "main"

    # Mirrors .github/workflows/package-dmg.yml's brew install line + setup-go +
    # rust-toolchain. The prebuilt (non-HEAD) release path needs none of these.
    depends_on "gettext" => :build
    depends_on "go" => :build
    depends_on "lld" => :build
    depends_on "llvm" => :build
    depends_on "pkg-config" => :build
    depends_on "rustup" => :build
    depends_on "umoci" => :build
    depends_on "util-linux" => :build
    depends_on "xz" => :build
  end

  depends_on arch: :arm64
  depends_on macos: :ventura

  def install
    if build.head?
      system "build/build-all.sh"
      system "build/sign.sh"
    end

    bin.install "vendor/bin/anylinuxfs"
    libexec.install "vendor/bin/gvproxy"
    libexec.install "vendor/bin/vmnet-helper"
    libexec.install "vendor/bin/vmproxy"
    libexec.install "vendor/bin/init-rootfs"
    libexec.install "vendor/kernel/Image"
    libexec.install "vendor/kernel/Image-4K"
    # init-rootfs's own copyLinuxModules() reads modules.squashfs from
    # prefixDir/lib/, not prefixDir/libexec/ — see install.sh for the same fix.
    lib.install "vendor/kernel/modules.squashfs"

    (libexec/"ntfsmac/commands").install Dir["cli/commands/*.sh"]
    (libexec/"ntfsmac/lib").install Dir["cli/lib/*.sh"]
    (libexec/"ntfsmac/lib").install "build/lib/lock.sh"
    (libexec/"ntfsmac").install "build/sources.lock"
    (libexec/"ntfsmac/pf").install Dir["cli/pf/*.tmpl"]
    if File.exist?("gui/Info.plist")
      (libexec/"ntfsmac/lib").install "gui/Info.plist" => "product-info.plist"
    elsif File.exist?("cli/lib/product-info.plist")
      (libexec/"ntfsmac/lib").install "cli/lib/product-info.plist"
    end
    Dir[libexec/"ntfsmac/commands/*.sh"].each { |f| chmod 0755, f }
    chmod 0755, libexec/"ntfsmac/lib/lock.sh"

    (bin/"ntfsmac").write <<~SH
      #!/bin/bash
      # Generated by Formula/ntfsmac.rb — dispatches to #{libexec}/ntfsmac/commands/*.sh.
      set -u
      LIBEXEC="#{libexec}/ntfsmac"

      print_help() {
        cat <<'HELP'
      usage: ntfsmac <command> [args...]

      commands:
        mount [device] [mount_point]       Mount an NTFS / ext drive (omit device to pick from a list).
                                            Flags: --preserve-private-relay, --fs-driver ntfs-3g|ntfs3, --read-only
        unmount [device|mount_point]       Unmount a drive (omit to pick from active mounts)
        diagnose [--json]                  Read-only health check
        uninstall [--force] [--keep-cache] Remove the CLI, vendored deps, and the GUI helper
        help                               Show this message

      'ntfsmac uninstall --help' shows uninstall's flags in detail.
      HELP
      }

      sub="${1:-}"
      [[ $# -gt 0 ]] && shift
      case "$sub" in
        mount) exec "$LIBEXEC/commands/mount.sh" "$@" ;;
        unmount) exec "$LIBEXEC/commands/unmount.sh" "$@" ;;
        diagnose) exec "$LIBEXEC/commands/diagnose.sh" "$@" ;;
        uninstall) exec "$LIBEXEC/commands/uninstall.sh" "$@" ;;
        help | --help | -h | "") print_help; exit 0 ;;
        *) echo "ntfsmac: unknown command '$sub'" >&2; print_help >&2; exit 1 ;;
      esac
    SH
  end

  def post_install
    quarantined = [bin/"anylinuxfs", libexec/"gvproxy", libexec/"vmnet-helper",
                   libexec/"vmproxy", libexec/"init-rootfs", bin/"ntfsmac",
                   libexec/"ntfsmac/lib/lock.sh"]
    quarantined.each do |f|
      next unless f.exist?

      quiet_system "xattr", "-d", "com.apple.quarantine", f.to_s
    end

    # Test/CI skip guard: keeps unit tests fast and deterministic
    return if ENV["NTFSMAC_SKIP_RUNTIME_INIT"] == "1" || ENV["HOMEBREW_NTFSMAC_SKIP_INIT"] == "1"

    # Start fresh: safely clear stale microVM caches unless an active NFS mount is present
    if system("/sbin/mount -t nfs 2>/dev/null | /usr/bin/grep -q .")
      opoo "Active NFS mount detected; skipping microVM cache wipe to prevent corruption."
    else
      rm_r Dir["#{Dir.home}/.anylinuxfs/alpine-*"], force: true
      rm_r Dir["#{Dir.home}/.anylinuxfs/*.preserved-*"], force: true
    end

    # Pre-install Alpine Linux microVM runtime start-to-finish so mount/list are instant
    if (bin/"anylinuxfs").exist?
      ohai "Setting up microVM environment and installing Alpine runtime (takes ~1-2 min)..."
      if system((bin/"anylinuxfs").to_s, "init")
        ohai "Environment setup complete — Alpine Linux runtime is ready."
      else
        opoo "Alpine microVM runtime initialization did not complete. It will be initialized on first mount."
      end
    end
  end

  # `brew uninstall` removes the Cellar tree + this Formula's own bin/libexec symlinks on its
  # own (standard Homebrew behavior, no ghost risk there) — but it has no idea about runtime
  # state anylinuxfs itself creates outside the Cellar (~/.anylinuxfs rootfs cache, per-run
  # logs). Mirrors cli/commands/uninstall.sh's remove_rootfs_cache/remove_logs (minus prefix
  # removal, which brew already owns) so a brew-tap uninstall leaves the same zero leftovers
  # an install.sh uninstall does. Runs unprivileged as the invoking user — never touches
  # /usr/local/ntfsmac or the GUI's privileged helper, both outside this Formula's own scope.
  def post_uninstall
    rm_r "#{Dir.home}/.anylinuxfs", force: true
    Dir.glob("#{Dir.home}/Library/Logs/anylinuxfs*.log").each { |f| rm f, force: true }
  end

  def caveats
    <<~EOS
      If you have the standalone anylinuxfs formula installed, link conflicts can be resolved by running:
        brew unlink anylinuxfs
        brew link --overwrite ntfsmac

      Full Disk Access (FDA):
      For Terminal to list or mount BitLocker or unpartitioned drives, grant Full Disk Access to your terminal application in:
        System Settings -> Privacy & Security -> Full Disk Access
    EOS
  end

  test do
    output = shell_output("#{bin}/ntfsmac diagnose --json")
    assert_match(/"healthy":\s*true/, output)
  end
end
